#pragma once

#include "esp_event.h"


ESP_EVENT_DECLARE_BASE(NETWORK_EVENT);
ESP_EVENT_DECLARE_BASE(PLAYBACK_EVENT);
ESP_EVENT_DECLARE_BASE(CONTROL_COMMAND);


typedef enum {
	NETWORK_EVENT_DISCONNECT,
	NETWORK_EVENT_CONNECT,
} network_event_t;


typedef enum {
	PLAYBACK_EVENT_START,
	PLAYBACK_EVENT_FINISH,
	PLAYBACK_EVENT_ERROR,
	PLAYBACK_EVENT_PLAYLIST_ITEM_CHANGE,
} playback_event_t;


typedef enum {
	CONTROL_COMMAND_STOP,
	CONTROL_COMMAND_START,
	CONTROL_COMMAND_QUIT,
	CONTROL_COMMAND_VOLUME_UP,
	CONTROL_COMMAND_VOLUME_DOWN,
	CONTROL_COMMAND_VOLUME_SET,
	CONTROL_COMMAND_SET_STREAM_URL,
} control_command_t;


extern esp_event_loop_handle_t player_event_loop;
